services:
  app:
    container_name: ptfl-app
    build: 
      context: .docker
      dockerfile: php.dockerfile
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html
    networks:
      - ptfl-ntwk
    depends_on:
      - db

  db:
    container_name: ptfl-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=thedarknine
      - MYSQL_PASSWORD=plop
    ports:
      - "3306:3306"
    networks:
      - ptfl-ntwk
    volumes:
      - db-data:/var/lib/mysql
      - ./.docker/volumes/logs/mysql:/var/log/mysql
      - ./.docker/mysql/ql:/docker-entrypoint-initdb.d
  
  engine:
    container_name: ptfl-server
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    networks:
      - ptfl-ntwk
  
  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    container_name: ptfl-pma
    ports:
        - 8088:80
    depends_on:
        - db
    restart: unless-stopped
    environment:
        PMA_HOST: db
        PMA_USER: thedarknine
        PMA_PASSWORD: plop
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    networks:
      - ptfl-ntwk

networks:
  ptfl-ntwk:
    driver: bridge

volumes:
  db-data: